# Generated by Django 5.2.3 on 2025-07-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_text', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTestResult',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='testresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychotest.question'),
        ),
    ]
